plugins {
    id 'com.android.application' version '8.10.1'
}

android {
    namespace 'com.ajmst.android'
    compileSdk 36

    defaultConfig {
        applicationId 'com.ajmst.android'
        minSdk 30
        targetSdk 36
        versionCode 3
        versionName '3.0'
    }

    buildTypes {
        debug {
            applicationIdSuffix '.recovered'
        }
    }

    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            java.srcDirs = ['src']
            res.srcDirs = ['res']
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
}
