package com.ajmst.commmon.entity;

// default package
// Generated 2013-12-1 1:00:31 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.table.DatabaseTable;

/**
 * AjmstMaintain generated by hbm2java
 * 删除复合主键类AjmstMaintainId,采用单一主键,cj,20131214
 */
@DatabaseTable
public class AjmstMaintain implements java.io.Serializable {

	private static final long serialVersionUID = 9093653695636464295L;
	@DatabaseField(id=true)
	private String id;
	@DatabaseField
	private String spid;
	@DatabaseField
	private String pihao;
	@DatabaseField
	private Double shl;
	@DatabaseField
	private Double suggestQuantity;
	@DatabaseField
	private String spbh;
	@DatabaseField
	private String spmch;
	@DatabaseField
	private String shengccj;
	@DatabaseField
	private String shpgg;
	@DatabaseField
	private String dw;
	@DatabaseField
	private String cabinetNo;
	@DatabaseField
	private String zjm;
	@DatabaseField
	private Date maintainDate;
	@DatabaseField
	private Date createTime;

	public AjmstMaintain() {
	}

	public AjmstMaintain(String id, String spid, String pihao, Date maintainDate) {
		this.id = id;
		this.spid = spid;
		this.pihao = pihao;
		this.maintainDate = maintainDate;
	}

	public AjmstMaintain(String id, String spid, String pihao, Double shl,
			Double suggestQuantity, String spbh, String spmch, String shengccj,
			String shpgg, String dw, String cabinetNo, String zjm,
			Date maintainDate, Date createTime) {
		this.id = id;
		this.spid = spid;
		this.pihao = pihao;
		this.shl = shl;
		this.suggestQuantity = suggestQuantity;
		this.spbh = spbh;
		this.spmch = spmch;
		this.shengccj = shengccj;
		this.shpgg = shpgg;
		this.dw = dw;
		this.cabinetNo = cabinetNo;
		this.zjm = zjm;
		this.maintainDate = maintainDate;
		this.createTime = createTime;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getSpid() {
		return this.spid;
	}

	public void setSpid(String spid) {
		this.spid = spid;
	}

	public String getPihao() {
		return this.pihao;
	}

	public void setPihao(String pihao) {
		this.pihao = pihao;
	}

	public Double getShl() {
		return this.shl;
	}

	public void setShl(Double shl) {
		this.shl = shl;
	}

	public Double getSuggestQuantity() {
		return this.suggestQuantity;
	}

	public void setSuggestQuantity(Double suggestQuantity) {
		this.suggestQuantity = suggestQuantity;
	}

	public String getSpbh() {
		return this.spbh;
	}

	public void setSpbh(String spbh) {
		this.spbh = spbh;
	}

	public String getSpmch() {
		return this.spmch;
	}

	public void setSpmch(String spmch) {
		this.spmch = spmch;
	}

	public String getShengccj() {
		return this.shengccj;
	}

	public void setShengccj(String shengccj) {
		this.shengccj = shengccj;
	}

	public String getShpgg() {
		return this.shpgg;
	}

	public void setShpgg(String shpgg) {
		this.shpgg = shpgg;
	}

	public String getDw() {
		return this.dw;
	}

	public void setDw(String dw) {
		this.dw = dw;
	}

	public String getCabinetNo() {
		return this.cabinetNo;
	}

	public void setCabinetNo(String cabinetNo) {
		this.cabinetNo = cabinetNo;
	}

	public String getZjm() {
		return this.zjm;
	}

	public void setZjm(String zjm) {
		this.zjm = zjm;
	}

	public Date getMaintainDate() {
		return this.maintainDate;
	}

	public void setMaintainDate(Date maintainDate) {
		this.maintainDate = maintainDate;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

}
