package com.ajmst.commmon.entity;

import com.j256.ormlite.field.DatabaseField;

// Generated 2013-11-6 22:08:05 by Hibernate Tools 3.4.0.CR1

/**
 * AjmstGh generated by hbm2java
 */
public class AjmstGh implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@DatabaseField
	private String spbh;
	@DatabaseField
	private String gh;
	@DatabaseField
	private String spid;

	public AjmstGh() {
	}

	public AjmstGh(String spbh, String gh) {
		this.spbh = spbh;
		this.gh = gh;
	}

	public AjmstGh(String spbh, String gh, String spid) {
		this.spbh = spbh;
		this.gh = gh;
		this.spid = spid;
	}

	public String getSpbh() {
		return this.spbh;
	}

	public void setSpbh(String spbh) {
		this.spbh = spbh;
	}

	public String getGh() {
		return this.gh;
	}

	public void setGh(String gh) {
		this.gh = gh;
	}

	public String getSpid() {
		return this.spid;
	}

	public void setSpid(String spid) {
		this.spid = spid;
	}

}
