package com.ajmst.commmon.entity;

// Generated 2013-11-19 19:01:23 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import com.j256.ormlite.field.DatabaseField;

/**
 * Spkfk generated by hbm2java
 */
public class Spkfk implements java.io.Serializable {

	private static final long serialVersionUID = -8078613384970325476L;
	@DatabaseField(id=true)
	private String spid;
	@DatabaseField(index=true)
	private String spbh;
	@DatabaseField(index=true)
	private String sptm;
	@DatabaseField(index=true)
	private String spmch;
	@DatabaseField(index=true)
	private String zjm;
	@DatabaseField
	private String beactive;@DatabaseField
	private String yishj;@DatabaseField
	private String isJzok;@DatabaseField
	private String isGdsj;@DatabaseField
	private String isGdzk;@DatabaseField
	private String isTjsp;@DatabaseField
	private String isHysp;@DatabaseField
	private String isGmp;@DatabaseField
	private String isGsp;@DatabaseField
	private String isSy;@DatabaseField
	private String isYp;@DatabaseField
	private String jingd;@DatabaseField
	private String denglrq;@DatabaseField
	private String gengxshj;@DatabaseField
	private String delrq;@DatabaseField
	private String chbjs;@DatabaseField
	private String dw;@DatabaseField
	private String shpchd;@DatabaseField
	private String shpgg;@DatabaseField
	private String kemuhao;@DatabaseField
	private String oldcode;@DatabaseField
	private String rkhw;@DatabaseField
	private String ckhw;@DatabaseField
	private String dwbh;@DatabaseField
	private String bzqfs;@DatabaseField
	private String fenlbh;@DatabaseField
	private String guojbh;@DatabaseField
	private String changjbh;@DatabaseField
	private String huaxm;@DatabaseField
	private String changym;@DatabaseField
	private String suming;@DatabaseField
	private String xiwname;@DatabaseField
	private String tongym;@DatabaseField
	private String shengccj;@DatabaseField
	private String pizhwh;@DatabaseField
	private String zhucsb;@DatabaseField
	private String jixing;@DatabaseField
	private String shiyzh;@DatabaseField
	private String bulfy;@DatabaseField
	private String chuczysx;@DatabaseField
	private String chuffl;@DatabaseField
	private String yaofpd;@DatabaseField
	private String yongfyyl;@DatabaseField
	private String jinjzh;@DatabaseField
	private String zhuysx;@DatabaseField
	private String yaowchf;@DatabaseField
	private String youxq;@DatabaseField
	private String shangplx;@DatabaseField
	private String guizbz;@DatabaseField
	private String yongyfl;@DatabaseField
	private String leibie;@DatabaseField
	private String kuansbh;@DatabaseField
	private String xslb;@DatabaseField
	private String colorbh;@DatabaseField
	private String chimbh;@DatabaseField
	private String classkey;@DatabaseField
	private String beizhu;@DatabaseField
	private Integer jlgg;@DatabaseField
	private Integer otd;@DatabaseField
	private Integer ordercycle;@DatabaseField
	private BigDecimal stkquot;@DatabaseField
	private Integer shl;@DatabaseField
	private BigDecimal shlv;@DatabaseField
	private BigDecimal hshjj;@DatabaseField
	private BigDecimal jj;@DatabaseField
	private BigDecimal shj;@DatabaseField
	private BigDecimal hshsj;@DatabaseField
	private BigDecimal lshj;@DatabaseField
	private BigDecimal koul;@DatabaseField
	private BigDecimal kcsx;@DatabaseField
	private BigDecimal kcxx;@DatabaseField
	private BigDecimal helkc;@DatabaseField
	private Integer bzqts;@DatabaseField
	private Integer yujts;@DatabaseField
	private BigDecimal zgshl;@DatabaseField
	private BigDecimal zhdcbj;@DatabaseField
	private BigDecimal zdshj;@DatabaseField
	private BigDecimal zgshj;@DatabaseField
	private BigDecimal zgjjxz;@DatabaseField
	private BigDecimal maolv;@DatabaseField
	private BigDecimal huiytj;@DatabaseField
	private Long itemlength;@DatabaseField
	private Long itemheight;@DatabaseField
	private Long itemwidth;@DatabaseField
	private Long weight;@DatabaseField
	private BigDecimal casevolume;@DatabaseField
	private BigDecimal caseweight;@DatabaseField
	private BigDecimal zuixdwtj;@DatabaseField
	private BigDecimal zuixdwzl;@DatabaseField
	private BigDecimal pfpj;@DatabaseField
	private String dispcolor;@DatabaseField
	private String jx;@DatabaseField
	private Integer bzgg;@DatabaseField
	private String lastmodifytime;@DatabaseField
	private String isCmd;@DatabaseField
	private String lsgg;@DatabaseField
	private String isZdyh;@DatabaseField
	private String isJkyp;@DatabaseField
	private Integer minshl;@DatabaseField
	private BigDecimal cxDjKl;@DatabaseField
	private String isCxDj;@DatabaseField
	private String zdyh;@DatabaseField
	private BigDecimal zdhyzklshj;@DatabaseField
	private String isCyhydz;@DatabaseField
	private BigDecimal huiyshl;@DatabaseField
	private String nocalcopys;@DatabaseField
	private BigDecimal chbdj;@DatabaseField
	private String fuzr;@DatabaseField
	private String glid;@DatabaseField
	private String isJsh;@DatabaseField
	private String isLc;@DatabaseField
	private String isZhongyao;@DatabaseField
	private String typeBh;@DatabaseField
	private BigDecimal tjYlshj;@DatabaseField
	private String isYbsp;@DatabaseField
	private BigDecimal ybZfbl;@DatabaseField
	private String ybSpbh;@DatabaseField
	private String username;@DatabaseField
	private String chargelb;@DatabaseField
	private String isSendybzx;@DatabaseField
	private String zhilbz;@DatabaseField
	private String laihdw;@DatabaseField
	private Integer zbz;@DatabaseField
	private String zbcode;

	public Spkfk() {
	}

	public Spkfk(String spid) {
		this.spid = spid;
	}

	public Spkfk(String spid, String spbh, String sptm, String spmch,
			String zjm, String beactive, String yishj, String isJzok,
			String isGdsj, String isGdzk, String isTjsp, String isHysp,
			String isGmp, String isGsp, String isSy, String isYp, String jingd,
			String denglrq, String gengxshj, String delrq, String chbjs,
			String dw, String shpchd, String shpgg, String kemuhao,
			String oldcode, String rkhw, String ckhw, String dwbh,
			String bzqfs, String fenlbh, String guojbh, String changjbh,
			String huaxm, String changym, String suming, String xiwname,
			String tongym, String shengccj, String pizhwh, String zhucsb,
			String jixing, String shiyzh, String bulfy, String chuczysx,
			String chuffl, String yaofpd, String yongfyyl, String jinjzh,
			String zhuysx, String yaowchf, String youxq, String shangplx,
			String guizbz, String yongyfl, String leibie, String kuansbh,
			String xslb, String colorbh, String chimbh, String classkey,
			String beizhu, Integer jlgg, Integer otd, Integer ordercycle,
			BigDecimal stkquot, Integer shl, BigDecimal shlv, BigDecimal hshjj,
			BigDecimal jj, BigDecimal shj, BigDecimal hshsj, BigDecimal lshj,
			BigDecimal koul, BigDecimal kcsx, BigDecimal kcxx,
			BigDecimal helkc, Integer bzqts, Integer yujts, BigDecimal zgshl,
			BigDecimal zhdcbj, BigDecimal zdshj, BigDecimal zgshj,
			BigDecimal zgjjxz, BigDecimal maolv, BigDecimal huiytj,
			Long itemlength, Long itemheight, Long itemwidth, Long weight,
			BigDecimal casevolume, BigDecimal caseweight, BigDecimal zuixdwtj,
			BigDecimal zuixdwzl, BigDecimal pfpj, String dispcolor, String jx,
			Integer bzgg, String lastmodifytime, String isCmd, String lsgg,
			String isZdyh, String isJkyp, Integer minshl, BigDecimal cxDjKl,
			String isCxDj, String zdyh, BigDecimal zdhyzklshj, String isCyhydz,
			BigDecimal huiyshl, String nocalcopys, BigDecimal chbdj,
			String fuzr, String glid, String isJsh, String isLc,
			String isZhongyao, String typeBh, BigDecimal tjYlshj,
			String isYbsp, BigDecimal ybZfbl, String ybSpbh, String username,
			String chargelb, String isSendybzx, String zhilbz, String laihdw,
			Integer zbz, String zbcode) {
		this.spid = spid;
		this.spbh = spbh;
		this.sptm = sptm;
		this.spmch = spmch;
		this.zjm = zjm;
		this.beactive = beactive;
		this.yishj = yishj;
		this.isJzok = isJzok;
		this.isGdsj = isGdsj;
		this.isGdzk = isGdzk;
		this.isTjsp = isTjsp;
		this.isHysp = isHysp;
		this.isGmp = isGmp;
		this.isGsp = isGsp;
		this.isSy = isSy;
		this.isYp = isYp;
		this.jingd = jingd;
		this.denglrq = denglrq;
		this.gengxshj = gengxshj;
		this.delrq = delrq;
		this.chbjs = chbjs;
		this.dw = dw;
		this.shpchd = shpchd;
		this.shpgg = shpgg;
		this.kemuhao = kemuhao;
		this.oldcode = oldcode;
		this.rkhw = rkhw;
		this.ckhw = ckhw;
		this.dwbh = dwbh;
		this.bzqfs = bzqfs;
		this.fenlbh = fenlbh;
		this.guojbh = guojbh;
		this.changjbh = changjbh;
		this.huaxm = huaxm;
		this.changym = changym;
		this.suming = suming;
		this.xiwname = xiwname;
		this.tongym = tongym;
		this.shengccj = shengccj;
		this.pizhwh = pizhwh;
		this.zhucsb = zhucsb;
		this.jixing = jixing;
		this.shiyzh = shiyzh;
		this.bulfy = bulfy;
		this.chuczysx = chuczysx;
		this.chuffl = chuffl;
		this.yaofpd = yaofpd;
		this.yongfyyl = yongfyyl;
		this.jinjzh = jinjzh;
		this.zhuysx = zhuysx;
		this.yaowchf = yaowchf;
		this.youxq = youxq;
		this.shangplx = shangplx;
		this.guizbz = guizbz;
		this.yongyfl = yongyfl;
		this.leibie = leibie;
		this.kuansbh = kuansbh;
		this.xslb = xslb;
		this.colorbh = colorbh;
		this.chimbh = chimbh;
		this.classkey = classkey;
		this.beizhu = beizhu;
		this.jlgg = jlgg;
		this.otd = otd;
		this.ordercycle = ordercycle;
		this.stkquot = stkquot;
		this.shl = shl;
		this.shlv = shlv;
		this.hshjj = hshjj;
		this.jj = jj;
		this.shj = shj;
		this.hshsj = hshsj;
		this.lshj = lshj;
		this.koul = koul;
		this.kcsx = kcsx;
		this.kcxx = kcxx;
		this.helkc = helkc;
		this.bzqts = bzqts;
		this.yujts = yujts;
		this.zgshl = zgshl;
		this.zhdcbj = zhdcbj;
		this.zdshj = zdshj;
		this.zgshj = zgshj;
		this.zgjjxz = zgjjxz;
		this.maolv = maolv;
		this.huiytj = huiytj;
		this.itemlength = itemlength;
		this.itemheight = itemheight;
		this.itemwidth = itemwidth;
		this.weight = weight;
		this.casevolume = casevolume;
		this.caseweight = caseweight;
		this.zuixdwtj = zuixdwtj;
		this.zuixdwzl = zuixdwzl;
		this.pfpj = pfpj;
		this.dispcolor = dispcolor;
		this.jx = jx;
		this.bzgg = bzgg;
		this.lastmodifytime = lastmodifytime;
		this.isCmd = isCmd;
		this.lsgg = lsgg;
		this.isZdyh = isZdyh;
		this.isJkyp = isJkyp;
		this.minshl = minshl;
		this.cxDjKl = cxDjKl;
		this.isCxDj = isCxDj;
		this.zdyh = zdyh;
		this.zdhyzklshj = zdhyzklshj;
		this.isCyhydz = isCyhydz;
		this.huiyshl = huiyshl;
		this.nocalcopys = nocalcopys;
		this.chbdj = chbdj;
		this.fuzr = fuzr;
		this.glid = glid;
		this.isJsh = isJsh;
		this.isLc = isLc;
		this.isZhongyao = isZhongyao;
		this.typeBh = typeBh;
		this.tjYlshj = tjYlshj;
		this.isYbsp = isYbsp;
		this.ybZfbl = ybZfbl;
		this.ybSpbh = ybSpbh;
		this.username = username;
		this.chargelb = chargelb;
		this.isSendybzx = isSendybzx;
		this.zhilbz = zhilbz;
		this.laihdw = laihdw;
		this.zbz = zbz;
		this.zbcode = zbcode;
	}

	public String getSpid() {
		return this.spid;
	}

	public void setSpid(String spid) {
		this.spid = spid;
	}

	public String getSpbh() {
		return this.spbh;
	}

	public void setSpbh(String spbh) {
		this.spbh = spbh;
	}

	public String getSptm() {
		return this.sptm;
	}

	public void setSptm(String sptm) {
		this.sptm = sptm;
	}

	public String getSpmch() {
		return this.spmch;
	}

	public void setSpmch(String spmch) {
		this.spmch = spmch;
	}

	public String getZjm() {
		return this.zjm;
	}

	public void setZjm(String zjm) {
		this.zjm = zjm;
	}

	public String getBeactive() {
		return this.beactive;
	}

	public void setBeactive(String beactive) {
		this.beactive = beactive;
	}

	public String getYishj() {
		return this.yishj;
	}

	public void setYishj(String yishj) {
		this.yishj = yishj;
	}

	public String getIsJzok() {
		return this.isJzok;
	}

	public void setIsJzok(String isJzok) {
		this.isJzok = isJzok;
	}

	public String getIsGdsj() {
		return this.isGdsj;
	}

	public void setIsGdsj(String isGdsj) {
		this.isGdsj = isGdsj;
	}

	public String getIsGdzk() {
		return this.isGdzk;
	}

	public void setIsGdzk(String isGdzk) {
		this.isGdzk = isGdzk;
	}

	public String getIsTjsp() {
		return this.isTjsp;
	}

	public void setIsTjsp(String isTjsp) {
		this.isTjsp = isTjsp;
	}

	public String getIsHysp() {
		return this.isHysp;
	}

	public void setIsHysp(String isHysp) {
		this.isHysp = isHysp;
	}

	public String getIsGmp() {
		return this.isGmp;
	}

	public void setIsGmp(String isGmp) {
		this.isGmp = isGmp;
	}

	public String getIsGsp() {
		return this.isGsp;
	}

	public void setIsGsp(String isGsp) {
		this.isGsp = isGsp;
	}

	public String getIsSy() {
		return this.isSy;
	}

	public void setIsSy(String isSy) {
		this.isSy = isSy;
	}

	public String getIsYp() {
		return this.isYp;
	}

	public void setIsYp(String isYp) {
		this.isYp = isYp;
	}

	public String getJingd() {
		return this.jingd;
	}

	public void setJingd(String jingd) {
		this.jingd = jingd;
	}

	public String getDenglrq() {
		return this.denglrq;
	}

	public void setDenglrq(String denglrq) {
		this.denglrq = denglrq;
	}

	public String getGengxshj() {
		return this.gengxshj;
	}

	public void setGengxshj(String gengxshj) {
		this.gengxshj = gengxshj;
	}

	public String getDelrq() {
		return this.delrq;
	}

	public void setDelrq(String delrq) {
		this.delrq = delrq;
	}

	public String getChbjs() {
		return this.chbjs;
	}

	public void setChbjs(String chbjs) {
		this.chbjs = chbjs;
	}

	public String getDw() {
		return this.dw;
	}

	public void setDw(String dw) {
		this.dw = dw;
	}

	public String getShpchd() {
		return this.shpchd;
	}

	public void setShpchd(String shpchd) {
		this.shpchd = shpchd;
	}

	public String getShpgg() {
		return this.shpgg;
	}

	public void setShpgg(String shpgg) {
		this.shpgg = shpgg;
	}

	public String getKemuhao() {
		return this.kemuhao;
	}

	public void setKemuhao(String kemuhao) {
		this.kemuhao = kemuhao;
	}

	public String getOldcode() {
		return this.oldcode;
	}

	public void setOldcode(String oldcode) {
		this.oldcode = oldcode;
	}

	public String getRkhw() {
		return this.rkhw;
	}

	public void setRkhw(String rkhw) {
		this.rkhw = rkhw;
	}

	public String getCkhw() {
		return this.ckhw;
	}

	public void setCkhw(String ckhw) {
		this.ckhw = ckhw;
	}

	public String getDwbh() {
		return this.dwbh;
	}

	public void setDwbh(String dwbh) {
		this.dwbh = dwbh;
	}

	public String getBzqfs() {
		return this.bzqfs;
	}

	public void setBzqfs(String bzqfs) {
		this.bzqfs = bzqfs;
	}

	public String getFenlbh() {
		return this.fenlbh;
	}

	public void setFenlbh(String fenlbh) {
		this.fenlbh = fenlbh;
	}

	public String getGuojbh() {
		return this.guojbh;
	}

	public void setGuojbh(String guojbh) {
		this.guojbh = guojbh;
	}

	public String getChangjbh() {
		return this.changjbh;
	}

	public void setChangjbh(String changjbh) {
		this.changjbh = changjbh;
	}

	public String getHuaxm() {
		return this.huaxm;
	}

	public void setHuaxm(String huaxm) {
		this.huaxm = huaxm;
	}

	public String getChangym() {
		return this.changym;
	}

	public void setChangym(String changym) {
		this.changym = changym;
	}

	public String getSuming() {
		return this.suming;
	}

	public void setSuming(String suming) {
		this.suming = suming;
	}

	public String getXiwname() {
		return this.xiwname;
	}

	public void setXiwname(String xiwname) {
		this.xiwname = xiwname;
	}

	public String getTongym() {
		return this.tongym;
	}

	public void setTongym(String tongym) {
		this.tongym = tongym;
	}

	public String getShengccj() {
		return this.shengccj;
	}

	public void setShengccj(String shengccj) {
		this.shengccj = shengccj;
	}

	public String getPizhwh() {
		return this.pizhwh;
	}

	public void setPizhwh(String pizhwh) {
		this.pizhwh = pizhwh;
	}

	public String getZhucsb() {
		return this.zhucsb;
	}

	public void setZhucsb(String zhucsb) {
		this.zhucsb = zhucsb;
	}

	public String getJixing() {
		return this.jixing;
	}

	public void setJixing(String jixing) {
		this.jixing = jixing;
	}

	public String getShiyzh() {
		return this.shiyzh;
	}

	public void setShiyzh(String shiyzh) {
		this.shiyzh = shiyzh;
	}

	public String getBulfy() {
		return this.bulfy;
	}

	public void setBulfy(String bulfy) {
		this.bulfy = bulfy;
	}

	public String getChuczysx() {
		return this.chuczysx;
	}

	public void setChuczysx(String chuczysx) {
		this.chuczysx = chuczysx;
	}

	public String getChuffl() {
		return this.chuffl;
	}

	public void setChuffl(String chuffl) {
		this.chuffl = chuffl;
	}

	public String getYaofpd() {
		return this.yaofpd;
	}

	public void setYaofpd(String yaofpd) {
		this.yaofpd = yaofpd;
	}

	public String getYongfyyl() {
		return this.yongfyyl;
	}

	public void setYongfyyl(String yongfyyl) {
		this.yongfyyl = yongfyyl;
	}

	public String getJinjzh() {
		return this.jinjzh;
	}

	public void setJinjzh(String jinjzh) {
		this.jinjzh = jinjzh;
	}

	public String getZhuysx() {
		return this.zhuysx;
	}

	public void setZhuysx(String zhuysx) {
		this.zhuysx = zhuysx;
	}

	public String getYaowchf() {
		return this.yaowchf;
	}

	public void setYaowchf(String yaowchf) {
		this.yaowchf = yaowchf;
	}

	public String getYouxq() {
		return this.youxq;
	}

	public void setYouxq(String youxq) {
		this.youxq = youxq;
	}

	public String getShangplx() {
		return this.shangplx;
	}

	public void setShangplx(String shangplx) {
		this.shangplx = shangplx;
	}

	public String getGuizbz() {
		return this.guizbz;
	}

	public void setGuizbz(String guizbz) {
		this.guizbz = guizbz;
	}

	public String getYongyfl() {
		return this.yongyfl;
	}

	public void setYongyfl(String yongyfl) {
		this.yongyfl = yongyfl;
	}

	public String getLeibie() {
		return this.leibie;
	}

	public void setLeibie(String leibie) {
		this.leibie = leibie;
	}

	public String getKuansbh() {
		return this.kuansbh;
	}

	public void setKuansbh(String kuansbh) {
		this.kuansbh = kuansbh;
	}

	public String getXslb() {
		return this.xslb;
	}

	public void setXslb(String xslb) {
		this.xslb = xslb;
	}

	public String getColorbh() {
		return this.colorbh;
	}

	public void setColorbh(String colorbh) {
		this.colorbh = colorbh;
	}

	public String getChimbh() {
		return this.chimbh;
	}

	public void setChimbh(String chimbh) {
		this.chimbh = chimbh;
	}

	public String getClasskey() {
		return this.classkey;
	}

	public void setClasskey(String classkey) {
		this.classkey = classkey;
	}

	public String getBeizhu() {
		return this.beizhu;
	}

	public void setBeizhu(String beizhu) {
		this.beizhu = beizhu;
	}

	public Integer getJlgg() {
		return this.jlgg;
	}

	public void setJlgg(Integer jlgg) {
		this.jlgg = jlgg;
	}

	public Integer getOtd() {
		return this.otd;
	}

	public void setOtd(Integer otd) {
		this.otd = otd;
	}

	public Integer getOrdercycle() {
		return this.ordercycle;
	}

	public void setOrdercycle(Integer ordercycle) {
		this.ordercycle = ordercycle;
	}

	public BigDecimal getStkquot() {
		return this.stkquot;
	}

	public void setStkquot(BigDecimal stkquot) {
		this.stkquot = stkquot;
	}

	public Integer getShl() {
		return this.shl;
	}

	public void setShl(Integer shl) {
		this.shl = shl;
	}

	public BigDecimal getShlv() {
		return this.shlv;
	}

	public void setShlv(BigDecimal shlv) {
		this.shlv = shlv;
	}

	public BigDecimal getHshjj() {
		return this.hshjj;
	}

	public void setHshjj(BigDecimal hshjj) {
		this.hshjj = hshjj;
	}

	public BigDecimal getJj() {
		return this.jj;
	}

	public void setJj(BigDecimal jj) {
		this.jj = jj;
	}

	public BigDecimal getShj() {
		return this.shj;
	}

	public void setShj(BigDecimal shj) {
		this.shj = shj;
	}

	public BigDecimal getHshsj() {
		return this.hshsj;
	}

	public void setHshsj(BigDecimal hshsj) {
		this.hshsj = hshsj;
	}

	public BigDecimal getLshj() {
		return this.lshj;
	}

	public void setLshj(BigDecimal lshj) {
		this.lshj = lshj;
	}

	public BigDecimal getKoul() {
		return this.koul;
	}

	public void setKoul(BigDecimal koul) {
		this.koul = koul;
	}

	public BigDecimal getKcsx() {
		return this.kcsx;
	}

	public void setKcsx(BigDecimal kcsx) {
		this.kcsx = kcsx;
	}

	public BigDecimal getKcxx() {
		return this.kcxx;
	}

	public void setKcxx(BigDecimal kcxx) {
		this.kcxx = kcxx;
	}

	public BigDecimal getHelkc() {
		return this.helkc;
	}

	public void setHelkc(BigDecimal helkc) {
		this.helkc = helkc;
	}

	public Integer getBzqts() {
		return this.bzqts;
	}

	public void setBzqts(Integer bzqts) {
		this.bzqts = bzqts;
	}

	public Integer getYujts() {
		return this.yujts;
	}

	public void setYujts(Integer yujts) {
		this.yujts = yujts;
	}

	public BigDecimal getZgshl() {
		return this.zgshl;
	}

	public void setZgshl(BigDecimal zgshl) {
		this.zgshl = zgshl;
	}

	public BigDecimal getZhdcbj() {
		return this.zhdcbj;
	}

	public void setZhdcbj(BigDecimal zhdcbj) {
		this.zhdcbj = zhdcbj;
	}

	public BigDecimal getZdshj() {
		return this.zdshj;
	}

	public void setZdshj(BigDecimal zdshj) {
		this.zdshj = zdshj;
	}

	public BigDecimal getZgshj() {
		return this.zgshj;
	}

	public void setZgshj(BigDecimal zgshj) {
		this.zgshj = zgshj;
	}

	public BigDecimal getZgjjxz() {
		return this.zgjjxz;
	}

	public void setZgjjxz(BigDecimal zgjjxz) {
		this.zgjjxz = zgjjxz;
	}

	public BigDecimal getMaolv() {
		return this.maolv;
	}

	public void setMaolv(BigDecimal maolv) {
		this.maolv = maolv;
	}

	public BigDecimal getHuiytj() {
		return this.huiytj;
	}

	public void setHuiytj(BigDecimal huiytj) {
		this.huiytj = huiytj;
	}

	public Long getItemlength() {
		return this.itemlength;
	}

	public void setItemlength(Long itemlength) {
		this.itemlength = itemlength;
	}

	public Long getItemheight() {
		return this.itemheight;
	}

	public void setItemheight(Long itemheight) {
		this.itemheight = itemheight;
	}

	public Long getItemwidth() {
		return this.itemwidth;
	}

	public void setItemwidth(Long itemwidth) {
		this.itemwidth = itemwidth;
	}

	public Long getWeight() {
		return this.weight;
	}

	public void setWeight(Long weight) {
		this.weight = weight;
	}

	public BigDecimal getCasevolume() {
		return this.casevolume;
	}

	public void setCasevolume(BigDecimal casevolume) {
		this.casevolume = casevolume;
	}

	public BigDecimal getCaseweight() {
		return this.caseweight;
	}

	public void setCaseweight(BigDecimal caseweight) {
		this.caseweight = caseweight;
	}

	public BigDecimal getZuixdwtj() {
		return this.zuixdwtj;
	}

	public void setZuixdwtj(BigDecimal zuixdwtj) {
		this.zuixdwtj = zuixdwtj;
	}

	public BigDecimal getZuixdwzl() {
		return this.zuixdwzl;
	}

	public void setZuixdwzl(BigDecimal zuixdwzl) {
		this.zuixdwzl = zuixdwzl;
	}

	public BigDecimal getPfpj() {
		return this.pfpj;
	}

	public void setPfpj(BigDecimal pfpj) {
		this.pfpj = pfpj;
	}

	public String getDispcolor() {
		return this.dispcolor;
	}

	public void setDispcolor(String dispcolor) {
		this.dispcolor = dispcolor;
	}

	public String getJx() {
		return this.jx;
	}

	public void setJx(String jx) {
		this.jx = jx;
	}

	public Integer getBzgg() {
		return this.bzgg;
	}

	public void setBzgg(Integer bzgg) {
		this.bzgg = bzgg;
	}

	public String getLastmodifytime() {
		return this.lastmodifytime;
	}

	public void setLastmodifytime(String lastmodifytime) {
		this.lastmodifytime = lastmodifytime;
	}

	public String getIsCmd() {
		return this.isCmd;
	}

	public void setIsCmd(String isCmd) {
		this.isCmd = isCmd;
	}

	public String getLsgg() {
		return this.lsgg;
	}

	public void setLsgg(String lsgg) {
		this.lsgg = lsgg;
	}

	public String getIsZdyh() {
		return this.isZdyh;
	}

	public void setIsZdyh(String isZdyh) {
		this.isZdyh = isZdyh;
	}

	public String getIsJkyp() {
		return this.isJkyp;
	}

	public void setIsJkyp(String isJkyp) {
		this.isJkyp = isJkyp;
	}

	public Integer getMinshl() {
		return this.minshl;
	}

	public void setMinshl(Integer minshl) {
		this.minshl = minshl;
	}

	public BigDecimal getCxDjKl() {
		return this.cxDjKl;
	}

	public void setCxDjKl(BigDecimal cxDjKl) {
		this.cxDjKl = cxDjKl;
	}

	public String getIsCxDj() {
		return this.isCxDj;
	}

	public void setIsCxDj(String isCxDj) {
		this.isCxDj = isCxDj;
	}

	public String getZdyh() {
		return this.zdyh;
	}

	public void setZdyh(String zdyh) {
		this.zdyh = zdyh;
	}

	public BigDecimal getZdhyzklshj() {
		return this.zdhyzklshj;
	}

	public void setZdhyzklshj(BigDecimal zdhyzklshj) {
		this.zdhyzklshj = zdhyzklshj;
	}

	public String getIsCyhydz() {
		return this.isCyhydz;
	}

	public void setIsCyhydz(String isCyhydz) {
		this.isCyhydz = isCyhydz;
	}

	public BigDecimal getHuiyshl() {
		return this.huiyshl;
	}

	public void setHuiyshl(BigDecimal huiyshl) {
		this.huiyshl = huiyshl;
	}

	public String getNocalcopys() {
		return this.nocalcopys;
	}

	public void setNocalcopys(String nocalcopys) {
		this.nocalcopys = nocalcopys;
	}

	public BigDecimal getChbdj() {
		return this.chbdj;
	}

	public void setChbdj(BigDecimal chbdj) {
		this.chbdj = chbdj;
	}

	public String getFuzr() {
		return this.fuzr;
	}

	public void setFuzr(String fuzr) {
		this.fuzr = fuzr;
	}

	public String getGlid() {
		return this.glid;
	}

	public void setGlid(String glid) {
		this.glid = glid;
	}

	public String getIsJsh() {
		return this.isJsh;
	}

	public void setIsJsh(String isJsh) {
		this.isJsh = isJsh;
	}

	public String getIsLc() {
		return this.isLc;
	}

	public void setIsLc(String isLc) {
		this.isLc = isLc;
	}

	public String getIsZhongyao() {
		return this.isZhongyao;
	}

	public void setIsZhongyao(String isZhongyao) {
		this.isZhongyao = isZhongyao;
	}

	public String getTypeBh() {
		return this.typeBh;
	}

	public void setTypeBh(String typeBh) {
		this.typeBh = typeBh;
	}

	public BigDecimal getTjYlshj() {
		return this.tjYlshj;
	}

	public void setTjYlshj(BigDecimal tjYlshj) {
		this.tjYlshj = tjYlshj;
	}

	public String getIsYbsp() {
		return this.isYbsp;
	}

	public void setIsYbsp(String isYbsp) {
		this.isYbsp = isYbsp;
	}

	public BigDecimal getYbZfbl() {
		return this.ybZfbl;
	}

	public void setYbZfbl(BigDecimal ybZfbl) {
		this.ybZfbl = ybZfbl;
	}

	public String getYbSpbh() {
		return this.ybSpbh;
	}

	public void setYbSpbh(String ybSpbh) {
		this.ybSpbh = ybSpbh;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getChargelb() {
		return this.chargelb;
	}

	public void setChargelb(String chargelb) {
		this.chargelb = chargelb;
	}

	public String getIsSendybzx() {
		return this.isSendybzx;
	}

	public void setIsSendybzx(String isSendybzx) {
		this.isSendybzx = isSendybzx;
	}

	public String getZhilbz() {
		return this.zhilbz;
	}

	public void setZhilbz(String zhilbz) {
		this.zhilbz = zhilbz;
	}

	public String getLaihdw() {
		return this.laihdw;
	}

	public void setLaihdw(String laihdw) {
		this.laihdw = laihdw;
	}

	public Integer getZbz() {
		return this.zbz;
	}

	public void setZbz(Integer zbz) {
		this.zbz = zbz;
	}

	public String getZbcode() {
		return this.zbcode;
	}

	public void setZbcode(String zbcode) {
		this.zbcode = zbcode;
	}

}
